# Generated by Django 3.2.23 on 2023-12-17 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20231216_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdiscount',
            options={'verbose_name_plural': 'Discount Codes'},
        ),
    ]
