# Generated by Django 3.2.23 on 2023-12-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20231130_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='portions',
        ),
        migrations.AddField(
            model_name='product',
            name='portion_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='portion_unit',
            field=models.CharField(default='g', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.IntegerField(default=1),
        ),
    ]
