# Generated by Django 3.2.23 on 2023-12-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20231201_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
