# Generated by Django 3.2.23 on 2023-12-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
