# Generated by Django 3.2.23 on 2023-12-02 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_size_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalinfo',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_infos', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutritional_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutritional_infos', to='products.nutritionalinfo'),
        ),
    ]
