# Generated by Django 3.2.23 on 2023-12-02 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20231202_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutritionalinfo',
            old_name='fiber',
            new_name='fibre',
        ),
    ]
