# Generated by Django 3.2.23 on 2023-12-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_fiber_nutritionalinfo_fibre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalinfo',
            name='carbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionalinfo',
            name='fat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionalinfo',
            name='fibre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionalinfo',
            name='protein',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionalinfo',
            name='salt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionalinfo',
            name='saturated_fat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionalinfo',
            name='sugar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
