# Generated by Django 3.2.23 on 2023-12-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_has_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(default=False),
        ),
    ]
