# Generated by Django 3.2.23 on 2023-12-14 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20231213_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nutritional_info',
        ),
    ]
