# Generated by Django 3.2.23 on 2023-12-14 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_nutritional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nutritional_info',
        ),
    ]
