# Generated by Django 3.2.23 on 2023-12-17 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_remove_product_nutritional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionalinfo',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutritional_info', to='products.product'),
        ),
    ]
